### ISSUE TITLE
About transaction location 

### ISSUE THREAD

**Issue by AdamGreem** [aydenp/Bank#21]
When I run the app in swift, all the functions are working. But the location including (address, city, zip code, etc.) show the value is `null`. I wonder if there is no location data or I did wrong.

**Comment by aydenp** [comment]
It could be because not every transaction provides information about its location. Could you provide more information about how you set it up and determined this?

**Comment by AdamGreem** [comment]
I want to add another subtitle of transaction location in prototype cells. But transaction location item never show on table view. When I run the program, the swift shows the part of address contents are `null`. Therefore, I thought the transaction location item doesn't show up due to the location values are `null`. I attach the screen shot below include the code I add for location item and the information provided by swift.
<img width="200" alt="transaction location in cells" src="https://user-images.githubusercontent.com/45516604/49455361-0b911980-f7b5-11e8-9004-39cc0cf46897.png">
<img width="531" alt="code for transaction location" src="https://user-images.githubusercontent.com/45516604/49455429-2c596f00-f7b5-11e8-88ac-be1830f5a34c.png">
<img width="391" alt="information" src="https://user-images.githubusercontent.com/45516604/49455669-82c6ad80-f7b5-11e8-9cc3-7b1cb05f3a27.png">

**Comment by aydenp** [comment]
Is that data from the console deserialized from the Codable model or a dictionary? Could you post the JSON string returned?

**Comment by aydenp** [comment]
Also, the data shows that it’s an interest payment, which I’m assuming wouldn’t have a location associated with it (usually those come with physical in-person transactions)

**Comment by AdamGreem** [comment]
I download your package and run your code in swift. I have followed your instruction. The data is shown in swift. I attached the screen shot of where data from below. Sorry, I am new in this field, so thank you for your help.
<img width="1425" alt="screen shot 2018-12-04 at 11 56 27 am" src="https://user-images.githubusercontent.com/45516604/49458948-e3f17f80-f7bb-11e8-9a8d-3dd694415565.png">

**Comment by AdamGreem** [comment]
Hi, sorry for bothering you again. Last question, could you add logout feature in this project? Because I think people may have different bank account. Therefore, it will be more convenience if add log out feature.

**Comment by aydenp** [comment]
This is more of a side project that's mostly for experience and fun, so it's not meant to be feature-complete (at least right now), which is why it doesn't have a log out button. In my testing, I would just add the appropriate logout function from PlaidManager to the AppDelegate's didFinishLaunching method in order to trigger it. It's not convenient, but it works for testing.

You're free to add one if you think it would be useful and something you're interested in doing!

**Comment by AdamGreem** [comment]
Thank you so much.

**Comment by AdamGreem** [comment]
Thank you so much.
