### ISSUE TITLE
Doesn't Load

### ISSUE THREAD

**Issue by okezue** [aydenp/Bank#24]
I have Plaid API and everything but can I run this for sandbox, and also how do i put the plaid.example.plist file into plaid.plist? I keep encountering this error and that is why the code doesn't run.

**Comment by aydenp** [comment]
Could you attach the error you're getting? It'd help me figure out exactly what's going wrong here.

However, if you haven't been able to setup the Plaid.plist file, this is likely what is causing the issue. In Finder, you should be able to make a copy of Plaid.example.plist and rename it to Plaid.plist. Then, in there, you should be able to fill in your credentials as specified in the readme.

I'm going to close this issue as it doesn't appear to be specifically relevant to the repository and code itself, but you can reach me by the email on my GitHub profile. Let me know if you need any more help!
